# Generated by Django 4.0.2 on 2022-09-15 18:07

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_remove_post_tags_delete_tags_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(help_text='your email would not be published', max_length=254),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
