# Generated by Django 4.0.2 on 2022-09-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_email_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default='cover_images/default.png', upload_to='cover_images/'),
        ),
    ]
